In [209]:
import os
import pandas as pd
import numpy as np

In [210]:
def drop_columns(df, cols):
    """
    This function removes the columns from a DataFrame.
    """
    for col in cols:
        try:
            df.drop([col], axis=1, inplace=True)
        except Exception as e:
            print(f"Bir hata oluştu: {e}")

In [211]:
df = pd.concat(
    [pd.read_csv(f"kira_ham_parçalı/{file}", thousands=".") for file in files],
    ignore_index=True
)

In [212]:
df["list-view-price"].unique()


array([  72500,   62500,   46500,   30000,   25000,   35000,   55000,
         75000,   45000,   23000,   80000,   32000,   38000,   19000,
         27500,   18500,   43000,   68000,   26000,   33000,   18000,
         36000,   52000,   17000,   60000,   41500,   20000,   28000,
         15000,   40000,   22800,   49000,   26500,   16500,   29000,
         24000,   21500,   12500,   22000,   21000,   17500,   23500,
         16000,   29500,   13000,   13500,   27000,    9500,   50000,
         32500,   25500,   34000,   31000,   10000,   30500,   23750,
         46000,   19500,   22500,   65000,   47000,   36500,   44000,
         12000,   70000,   39500,   39000,   13750,  395000,   11500,
         29995,   69000,   14000,   16250,    8000,   96000,   47500,
         14500,   28500,   42000,   37000,   11000,   15500,   10500,
         37500,   14250,    4000,    6000,   67000,   24500,  115000,
          9000,  195000,   51000,  200000,   45500,  100000,  180000,
        250000,  150

In [213]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   img-link href                        1596 non-null   object 
 1   photo-count                          1591 non-null   float64
 2   list-view-price                      1596 non-null   int64  
 3   list-view-date                       1596 non-null   object 
 4   left                                 1596 non-null   object 
 5   celly                                1596 non-null   object 
 6   celly 2                              1596 non-null   object 
 7   celly 3                              1596 non-null   object 
 8   celly 4                              1515 non-null   object 
 9   eids-badge__description              1457 non-null   object 
 10  he-lazy-image src                    1465 non-null   object 
 11  eids-badge__label             

In [214]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   img-link href                        1596 non-null   object 
 1   photo-count                          1591 non-null   float64
 2   list-view-price                      1596 non-null   int64  
 3   list-view-date                       1596 non-null   object 
 4   left                                 1596 non-null   object 
 5   celly                                1596 non-null   object 
 6   celly 2                              1596 non-null   object 
 7   celly 3                              1596 non-null   object 
 8   celly 4                              1515 non-null   object 
 9   eids-badge__description              1457 non-null   object 
 10  he-lazy-image src                    1465 non-null   object 
 11  eids-badge__label             

In [215]:
print(df.head(5))

                                       img-link href  photo-count  \
0  https://www.hepsiemlak.com/ankara-cankaya-kava...         39.0   
1  https://www.hepsiemlak.com/ankara-cankaya-kava...         45.0   
2  https://www.hepsiemlak.com/ankara-cankaya-kava...         38.0   
3  https://www.hepsiemlak.com/ankara-cankaya-yuka...         37.0   
4  https://www.hepsiemlak.com/ankara-altindag-dog...         19.0   

   list-view-price list-view-date           left  \
0            72500     28-04-2025  Kiralık Daire   
1            62500     28-04-2025  Kiralık Daire   
2            46500     28-04-2025  Kiralık Daire   
3            30000     08-05-2025  Kiralık Daire   
4            25000     04-05-2025  Kiralık Daire   

                              celly celly 2  \
0  2 +\n                          1   95 m²   
1  1 +\n                          1   65 m²   
2  1 +\n                          1   65 m²   
3  3 +\n                          1  115 m²   
4  3 +\n                          1  

In [216]:
print(df.columns)

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'left', 'celly', 'celly 2', 'celly 3', 'celly 4',
       'eids-badge__description', 'he-lazy-image src', 'eids-badge__label',
       'list-view-location', 'img-wrp href', 'he-lazy-image src 2',
       'img-wrp href 2', 'he-lazy-image src 3',
       'listing-card--owner-info__firm-name', 'listing-card--owner-info__name',
       'he-lazy-image src 4', 'list-view-header'],
      dtype='object')


In [217]:
cols = ['photo-count', 'list-view-date', 'list-view-header', 'list-view-location', "eids-badge__description",
    "eids-badge__label",
    "list-view-location",
    "img-wrp href",
    "he-lazy-image src",
    "img-wrp href 2",
    "he-lazy-image src 3",
    "listing-card--owner-info__firm-name",
    "listing-card--owner-info__name",
    "he-lazy-image src 4",
    "list-view-header"]
df = df.drop(columns=cols, errors='ignore')
df = df.drop(columns =["he-lazy-image src 2"],errors = 'ignore')

In [218]:
df.head()

img-link href  list-view-price  \
0  https://www.hepsiemlak.com/ankara-cankaya-kava...            72500   
1  https://www.hepsiemlak.com/ankara-cankaya-kava...            62500   
2  https://www.hepsiemlak.com/ankara-cankaya-kava...            46500   
3  https://www.hepsiemlak.com/ankara-cankaya-yuka...            30000   
4  https://www.hepsiemlak.com/ankara-altindag-dog...            25000   

            left                             celly celly 2  \
0  Kiralık Daire  2 +\n                          1   95 m²   
1  Kiralık Daire  1 +\n                          1   65 m²   
2  Kiralık Daire  1 +\n                          1   65 m²   
3  Kiralık Daire  3 +\n                          1  115 m²   
4  Kiralık Daire  3 +\n                          1  105 m²   

                               celly 3       celly 4  
0                           Sıfır Bina        2. Kat  
1                           Sıfır Bina        2. Kat  
2                           Sıfır Bina  Yüksek Giriş  
3  35\n                        Yaşında        2. Kat  
4                           Sıfır Bina        2. Kat

In [219]:
df["location"]= df["img-link href"].apply(lambda x:x.split('/')[3])
df["city"] = df["location"].str.split("-").str[0]
df["district"] = df["location"].str.split("-").str[1]
df["neighborhood"] = df["location"].str.split("-").str[2:-1]
df["neighborhood"] = df["neighborhood"].apply(lambda x: '_'.join(x))
print(df["neighborhood"].unique())

['kavaklidere' 'yukari_bahcelievler' 'dogantepe' 'oran' 'emek'
 'keklik_pinari' 'emniyet' 'guzeltepe' 'mursel_uluc' 'incek'
 'kirkkonaklar' 'cankaya' 'kizilcasar' 'durali_alic' 'gunesevler'
 'yasamkent' 'hacilar' 'alacaatli' 'sehit_cevdet_ozdemir' 'malazgirt'
 'ragip_tuzun' 'bahcelievler' 'ilkadim' 'mustafa_kemal' 'osmanli'
 'guvenevler' 'cukurambar' 'kayalar' 'balkiraz' 'bahcelerustu'
 'nasuh_akar' 'kavacik_subayevleri' 'ovecler' 'remzi_oguz_arik'
 'yildizevler' 'ilkbahar' 'yesilevler' 'ayvali' 'devlet' 'aksemsettin'
 'asagi_eglence' 'besikkaya' 'beytepe' 'yeni_baglica' 'gokturk' 'torekent'
 'yeni_bati' 'cumhuriyet' 'seker' 'umit' 'sehit_osman_avci' 'baglarbasi'
 'altay' 'ayranci' 'etlik' 'huzur' 'baglica' 'demetlale' 'cevizlidere'
 'eryaman' 'peyami_safa' 'gokkusagi' 'saimekadin' 'yukari_dikmen'
 'zubeyde_hanim' 'kamil_ocak' 'fahri_koruturk' 'sehitlik' 'segmenler'
 'aydinlikevler' 'tinaztepe' 'yukseltepe' 'ornek' 'bagcilar' 'murat'
 'zirvekent' 'gazi' 'konutkent' 'dodurga' 'maltepe' 

In [220]:
drop_columns(df,['location','img-link href'])

In [221]:
df.head()

list-view-price           left                             celly celly 2  \
0            72500  Kiralık Daire  2 +\n                          1   95 m²   
1            62500  Kiralık Daire  1 +\n                          1   65 m²   
2            46500  Kiralık Daire  1 +\n                          1   65 m²   
3            30000  Kiralık Daire  3 +\n                          1  115 m²   
4            25000  Kiralık Daire  3 +\n                          1  105 m²   

                               celly 3       celly 4    city  district  \
0                           Sıfır Bina        2. Kat  ankara   cankaya   
1                           Sıfır Bina        2. Kat  ankara   cankaya   
2                           Sıfır Bina  Yüksek Giriş  ankara   cankaya   
3  35\n                        Yaşında        2. Kat  ankara   cankaya   
4                           Sıfır Bina        2. Kat  ankara  altindag   

          neighborhood  
0          kavaklidere  
1          kavaklidere  
2          kavaklidere  
3  yukari_bahcelievler  
4            dogantepe

In [222]:
print(df["celly"].unique())

['2 +\n                          1' '1 +\n                          1'
 '3 +\n                          1' '4 +\n                          1'
 '5 +\n                          1' '7 +\n                          2'
 '4 +\n                          0' '1 +\n                          3'
 'Stüdyo' '9 +\n                          3'
 '4 +\n                          4' '3 +\n                          0'
 '6 +\n                          1' '3 +\n                          2'
 '2 +\n                          0' '5 +\n                          2'
 '1 +\n                          2' '6 +\n                          2'
 '6 +\n                          3' '2 +\n                          2'
 '4 +\n                          2' '8 +\n                          2'
 '6 +\n                          0' '8 +\n                          1']


In [223]:
df["celly"] = df["celly"].apply(lambda x: x.replace("Stüdyo", "1 + 0"))
df["celly"] = df["celly"].apply(lambda x: x.replace("\n", ""))
df["room"] = df["celly"].apply(lambda x: x.split("+")[0]).astype(int)
df["living_room"] = df["celly"].apply(lambda x: x.split("+")[1]).astype(int)

In [224]:
print(df["room"].unique())
print(df["living_room"].unique())

[2 1 3 4 5 7 9 6 8]
[1 2 0 3 4]


In [225]:
drop_columns(df,["celly"])

In [226]:
df.head()

list-view-price           left celly 2  \
0            72500  Kiralık Daire   95 m²   
1            62500  Kiralık Daire   65 m²   
2            46500  Kiralık Daire   65 m²   
3            30000  Kiralık Daire  115 m²   
4            25000  Kiralık Daire  105 m²   

                               celly 3       celly 4    city  district  \
0                           Sıfır Bina        2. Kat  ankara   cankaya   
1                           Sıfır Bina        2. Kat  ankara   cankaya   
2                           Sıfır Bina  Yüksek Giriş  ankara   cankaya   
3  35\n                        Yaşında        2. Kat  ankara   cankaya   
4                           Sıfır Bina        2. Kat  ankara  altindag   

          neighborhood  room  living_room  
0          kavaklidere     2            1  
1          kavaklidere     1            1  
2          kavaklidere     1            1  
3  yukari_bahcelievler     3            1  
4            dogantepe     3            1

In [227]:
print(df["celly 2"].unique())

['95 m²' '65 m²' '115 m²' '105 m²' '45 m²' '80 m²' '170 m²' '60 m²'
 '126 m²' '228 m²' '120 m²' '600 m²' '130 m²' '180 m²' '50 m²' '140 m²'
 '55 m²' '114 m²' '235 m²' '64 m²' '154 m²' '148 m²' '110 m²' '150 m²'
 '85 m²' '102 m²' '104 m²' '109 m²' '165 m²' '100 m²' '175 m²' '125 m²'
 '90 m²' '75 m²' '145 m²' '190 m²' '200 m²' '70 m²' '72 m²' '155 m²'
 '66 m²' '160 m²' '76 m²' '220 m²' '35 m²' '135 m²' '63 m²' '46 m²'
 '48 m²' '83 m²' '225 m²' '82 m²' '131 m²' '240 m²' '89 m²' '54 m²'
 '210 m²' '108 m²' '405 m²' '187 m²' '185 m²' '1.450 m²' '142 m²' '69 m²'
 '118 m²' '68 m²' '30 m²' '350 m²' '300 m²' '340 m²' '290 m²' '96 m²'
 '1.000 m²' '61 m²' '270 m²' '59 m²' '250 m²' '129 m²' '164 m²' '47 m²'
 '101 m²' '62 m²' '360 m²' '176 m²' '99 m²' '299 m²' '127 m²' '280 m²'
 '370 m²' '215 m²' '138 m²' '230 m²' '199 m²' '88 m²' '260 m²' '400 m²'
 '174 m²' '144 m²' '171 m²' '119 m²' '325 m²' '243 m²' '134 m²' '193 m²'
 '93 m²' '73 m²' '159 m²' '750 m²' '124 m²' '169 m²' '550 m²' '500 m²'
 '97 m²' 

In [228]:
df['celly 2'] = df["celly 2"].apply(lambda x: x.replace(".", ""))
df['area'] = df['celly 2'].apply(lambda x:x.split(" ")[0])

In [229]:
df['area'].astype(int)

0        95
1        65
2        65
3       115
4       105
       ... 
1591     55
1592     99
1593    165
1594     75
1595    155
Name: area, Length: 1596, dtype: int32

In [230]:
drop_columns(df, ["celly 2"])
df.head()

list-view-price           left                              celly 3  \
0            72500  Kiralık Daire                           Sıfır Bina   
1            62500  Kiralık Daire                           Sıfır Bina   
2            46500  Kiralık Daire                           Sıfır Bina   
3            30000  Kiralık Daire  35\n                        Yaşında   
4            25000  Kiralık Daire                           Sıfır Bina   

        celly 4    city  district         neighborhood  room  living_room area  
0        2. Kat  ankara   cankaya          kavaklidere     2            1   95  
1        2. Kat  ankara   cankaya          kavaklidere     1            1   65  
2  Yüksek Giriş  ankara   cankaya          kavaklidere     1            1   65  
3        2. Kat  ankara   cankaya  yukari_bahcelievler     3            1  115  
4        2. Kat  ankara  altindag            dogantepe     3            1  105

In [231]:
df["celly 3"].unique()

array(['Sıfır Bina', '35\n                        Yaşında',
       '38\n                        Yaşında',
       '17\n                        Yaşında',
       '1\n                        Yaşında',
       '2\n                        Yaşında',
       '20\n                        Yaşında',
       '7\n                        Yaşında',
       '15\n                        Yaşında',
       '25\n                        Yaşında',
       '10\n                        Yaşında',
       '13\n                        Yaşında',
       '5\n                        Yaşında',
       '8\n                        Yaşında',
       '26\n                        Yaşında',
       '30\n                        Yaşında',
       '21\n                        Yaşında',
       '40\n                        Yaşında',
       '33\n                        Yaşında',
       '45\n                        Yaşında',
       '55\n                        Yaşında',
       '18\n                        Yaşında',
       '50\n             

In [232]:
df["celly 3"] = df["celly 3"].apply(lambda x: x.replace("Sıfır Bina", "0 Yaşında"))
df["celly 3"] = df["celly 3"].apply(lambda x: x.replace("/n", " "))
df["age"] = df["celly 3"].apply(lambda x: x.split(" ")[0]).astype(int)


In [233]:
print(df["age"].unique())
drop_columns(df,["celly 3"])

[  0  35  38  17   1   2  20   7  15  25  10  13   5   8  26  30  21  40
  33  45  55  18  50  28   3  16  27   6  29  32  43  14  11   4  23   9
  24  60  37  12  34  22  42  31  19  47  44 452  39  46  52]


In [234]:
df.head()

list-view-price           left       celly 4    city  district  \
0            72500  Kiralık Daire        2. Kat  ankara   cankaya   
1            62500  Kiralık Daire        2. Kat  ankara   cankaya   
2            46500  Kiralık Daire  Yüksek Giriş  ankara   cankaya   
3            30000  Kiralık Daire        2. Kat  ankara   cankaya   
4            25000  Kiralık Daire        2. Kat  ankara  altindag   

          neighborhood  room  living_room area  age  
0          kavaklidere     2            1   95    0  
1          kavaklidere     1            1   65    0  
2          kavaklidere     1            1   65    0  
3  yukari_bahcelievler     3            1  115   35  
4            dogantepe     3            1  105    0

In [235]:
print(df["celly 4"].unique())

['2. Kat' 'Yüksek Giriş' 'Giriş Katı' '3. Kat' 'Ara Kat' '21 ve üzeri'
 'Zemin' nan '1. Kat' 'Kot 1' '5. Kat' '11. Kat' '4. Kat' '9. Kat'
 'Teras Katı' '8. Kat' '13. Kat' 'En Üst Kat' '6. Kat' 'Kot 2' '7. Kat'
 '19. Kat' '20. Kat' '10. Kat' 'Bahçe Katı' '14. Kat' 'Kot 3' '17. Kat'
 'Çatı Katı' 'Bodrum ve Zemin' '12. Kat' '16. Kat' 'Bodrum' 'Yarı Bodrum'
 'Villa Katı']


In [236]:
replace_dict = {
    'Kot 2': '-2. Kat',
    'Kot 1': '-1. Kat',
    'Yüksek Giriş': '1. Kat',
    'Ara Kat': '3. Kat',
    'En Üst Kat': '5. Kat',
    'Bahçe Katı': '0. Kat',
    'Yarı Bodrum': '0. Kat',
    'Bodrum': '0. Kat',
    'Kot 3': '-3. Kat',
    'Çatı Katı': '5. Kat',
    'Zemin': '0. Kat',
    'Giriş Katı': '0. Kat',
    'Villa Katı': '0. Kat',
    '21 ve üzeri': '21. Kat',
    'Bodrum ve Zemin': '0. Kat',
    'Tripleks': '0. Kat',
    'Teras Katı': '5. Kat',
    'nan': '2. Kat',
}

df['celly 4'] = df['celly 4'].fillna('2. Kat')
df['celly 4'] = df['celly 4'].replace(replace_dict.keys(), replace_dict.values()).astype(str)
df['floor'] = df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int)


In [239]:
print(df["floor"].unique())

[ 2  1  0  3 21 -1  5 11  4  9  8 13  6 -2  7 19 20 10 14 -3 17 12 16]


In [240]:
drop_columns(df, ["celly 4"])

In [242]:
drop_columns(df, ["left"])

In [243]:
df.head()

list-view-price    city  district         neighborhood  room  living_room  \
0            72500  ankara   cankaya          kavaklidere     2            1   
1            62500  ankara   cankaya          kavaklidere     1            1   
2            46500  ankara   cankaya          kavaklidere     1            1   
3            30000  ankara   cankaya  yukari_bahcelievler     3            1   
4            25000  ankara  altindag            dogantepe     3            1   

  area  age  floor  
0   95    0      2  
1   65    0      2  
2   65    0      1  
3  115   35      2  
4  105    0      2

In [244]:
print(df["list-view-price"].unique())

[  72500   62500   46500   30000   25000   35000   55000   75000   45000
   23000   80000   32000   38000   19000   27500   18500   43000   68000
   26000   33000   18000   36000   52000   17000   60000   41500   20000
   28000   15000   40000   22800   49000   26500   16500   29000   24000
   21500   12500   22000   21000   17500   23500   16000   29500   13000
   13500   27000    9500   50000   32500   25500   34000   31000   10000
   30500   23750   46000   19500   22500   65000   47000   36500   44000
   12000   70000   39500   39000   13750  395000   11500   29995   69000
   14000   16250    8000   96000   47500   14500   28500   42000   37000
   11000   15500   10500   37500   14250    4000    6000   67000   24500
  115000    9000  195000   51000  200000   45500  100000  180000  250000
  150000   57000   89000  270000  140000  360000  125000  130000  500000
  120000  265000  155000   53500   47800   38500   48500   85000  600000
  245000  185000  170000  165000  145000   90000   

In [245]:
df["price"]= df["list-view-price"].astype(int)

In [246]:
drop_columns(df, ["list-view-price"])

In [247]:
df.head()

city  district         neighborhood  room  living_room area  age  floor  \
0  ankara   cankaya          kavaklidere     2            1   95    0      2   
1  ankara   cankaya          kavaklidere     1            1   65    0      2   
2  ankara   cankaya          kavaklidere     1            1   65    0      1   
3  ankara   cankaya  yukari_bahcelievler     3            1  115   35      2   
4  ankara  altindag            dogantepe     3            1  105    0      2   

   price  
0  72500  
1  62500  
2  46500  
3  30000  
4  25000

In [248]:
df.to_csv('house_data',index=False)